blogdev/urls.py
from django.urls import path
from . import views

app_name='blogdev'

urlpatterns = [
    path('',views.index,name='index'),
    path('<int:id>/',views.post,name='post'),
    # path('tag/<slug:tag__slug>/',views.tagged,name='tagged'),
    path('search',views.search,name='search'),
]

sinhaladev/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static # new
from django.conf import settings # new


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('blogdev.urls')),
   
]

if settings.DEBUG: # new
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blogdev/models.py
from django.db import models
from django.db.models.deletion import CASCADE, PROTECT
from django_quill.fields import QuillField
from taggit.managers import TaggableManager

class Category(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name


class Post(models.Model):
    title = models.CharField(max_length=150)
    body = QuillField()
    created_at = models.DateTimeField(auto_now_add=True)
    modified_at = models.DateTimeField(auto_now=True)
    category = models.ForeignKey(Category, on_delete=CASCADE)
    tags = TaggableManager()
    cover_image = models.ImageField(upload_to='images/', null=True)

    def __str__(self):
        return self.title

blogdev/views.py
from typing import List
from django import http
from django.core import paginator
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponse

import blogdev
from . models import Post
from django.template import loader
from django.core.paginator import Paginator
from taggit.models import Tag
from django.views.generic import ListView
from django.db.models import Q



# Create your views here.
def index(request):
    posts = Post.objects.all()
    pages = Paginator(posts,3)
    page_number = request.GET.get('page')
    page_obj = pages.get_page(page_number)
    context = {
        'posts':page_obj
    }
    return render(request,'blogdev/post.html',context)
   
    

def post(request,id):
   post = get_object_or_404(Post,pk=id)
   return render(request,'blogdev/detail.html',{'post':post})


# def tagged(request,tag__slug=None):
#     if tag__slug:
#         tag = get_object_or_404(Tag,slug=tag__slug)
#         posts = Post.objects.all()
#         posts = posts.filter(tagged_items=[tag])
#         context = {
#             'tag':tag,
#             'posts':posts,
#         }
#         return render(request,'blogdev/tagview.html',context)


class tagListView(ListView):
    template_name = 'blogdev/tagview.html'

    def get_queryset(self):
        return Post.objects.filter(tags__slug=self.kwargs.get("slug"))
    
    def get_context_data(self, **kwargs):
        context = super(tagListView, self).get_context_data(**kwargs)
        context["tag"] = self.kwargs.get("slug")
        return context


def search(request):
    if request.method == 'POST':
        searched = request.POST['query']
        if searched:
            # posts = Post.objects.all()
            results = Post.objects.filter(title__contains=searched)
            context ={
                'posts':results
            }
            return render(request,'blogdev/results.html',context)
        else:
            return render(request,'blogdev/results.html')
    
        

blogdev/templates/blogdev/detail.html
{% extends "base.html" %}
{% block content %}
 
<article>
  <h1>{{post.title}}</h1>
  <p>{{post.body.html | safe }}</p>

</article>
  
{% endblock content %}

blogdev/templates/blogdev/post.html
{% extends "base.html" %}


{% block content %}
{% for post in posts  %}
 <div class="postcontainer">
    
   

 
      <div class="card mb-3" style="max-width: 540px;">
        <div class="row g-0">
          <div class="col-md-4">
            <img src="{{post.cover_image.url}}" class="img-fluid rounded-start" alt="...">
          </div>
          <div class="col-md-8">
            <div class="card-body">
              <h5 class="card-title">{{post.title}}</h5>
              <p class="card-text">This is a wider card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p>
              <p class="card-text"><small class="text-muted">Created at {{post.created_at}}</small></p>
              <p class="card-text"><small class="text-muted">Updated at {{post.modified_at}}</small></p>
              <a href="{{post.id}}" class="btn btn-primary" role="button">Read More</a>
            </div>
          </div>
        </div>
      </div>
 {% endfor %}
  <div aria-label="Page navigation example">
        
    {% if posts.has_previous %}
    
        <a href="?page={{posts.previous_page_number}}">previous</a>
    {% endif %}
    {% if posts.has_next %}
   
    <a href="?page={{posts.next_page_number}}">next</a>
{% endif %}
    
        
</div>
{% endblock content %}

blogdev/templates/blogdev/results.html
{% extends "base.html" %}

{% block content %}

{% if posts %}
{% for post in  posts %}
<p>{{post.id}}</p>
<p><a href="{{post.id}}">{{post.title}}</a></p>
  
{% endfor %}
{% else %}
<p>no search results</p>  
{% endif %}

{% endblock content %}

sinhaladev/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Open+Sans:wght@600&display=swap" rel="stylesheet"> 

    <link rel="stylesheet" type="text/css" href="{% static "css/main.css" %}">
    <script src="{% static "js/test.js" %}"></script>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-uWxY/CJNBR+1zjPWmfnSnVxwRheevXITnMqoEIeG1LJrdI0GlVs/9cVSyPYXdcSF" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-kQtW33rZJAHjgefvhyyzcGF3C5TFyBQBA13V1RKPf4uH+bwyzQxZ6CmMZHmNBEfJ" crossorigin="anonymous"></script>
    <title>Document</title>
    
</head>
<body>
    <!-- <div class="nav-container">
        <div class="nav-logo">
            <a href="/">Sinhala Dev</a>
        </div>
        <div class="nav-links">
            <ul class="nav-list">
                <li><a href="/">Home</a></li>
                <li><a href="/posts">Posts</a></li>
                <li><a href="/contact">Contact</a></li>
                <li><a href="/About">About</a></li>
            </ul>

        </div>
        <div class="searchbar">
            <form method="POST" action="{% url 'blogdev:search' %}">
                {% csrf_token %}
                <input type="search" name="query">
                <button type="submit">Search</button>
            </form>
        
        </div>

    </div>
     -->
     
     <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container-fluid">
          <a class="navbar-brand" href="#">SinhalaDEV</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="#">Home</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="#">Posts</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="#">Contact</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="#">About</a>
              </li>
        
        
            
            </ul>
            <form class="d-flex" method="POST" action="{% url 'blogdev:search' %}">
                {% csrf_token %}
              <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search" name="query">
              <button class="btn btn-outline-success" type="submit">Search</button>
            </form>
          </div>
        </div>
      </nav>
    
    <div class="container">
        {% block content %}{% endblock %}
    </div>
    
</body>
</html>